@echo off
cls


set PAS1=C
set PAS2=A
set PAS3=T
set PAS4=Z
set PAS5=Y
set PAS6=M
set PAS7=B
set PAS8=S
:LINE10
set STP1I=%RANDOM:~0,1%
IF "%STP1I%"=="0" GOTO NUBR1I
IF "%STP1I%"=="1" GOTO LTRS1I
IF "%STP1I%"=="2" GOTO NUBR1I
IF "%STP1I%"=="3" GOTO LTRS1I
IF "%STP1I%"=="4" GOTO NUBR1I
IF "%STP1I%"=="5" GOTO LTRS1I
IF "%STP1I%"=="6" GOTO NUBR1I
IF "%STP1I%"=="7" GOTO LTRS1I
IF "%STP1I%"=="8" GOTO NUBR1I
IF "%STP1I%"=="9" GOTO LTRS1I
:NUBR1I
set NUBR1I=%RANDOM:~0,1%
set PAS1=%NUBR1I%
goto LINE11
:LTRS1I
set LT1I=%RANDOM:~0,1%
IF "%LT1I%"=="0" GOTO TYPI
IF "%LT1I%"=="1" GOTO CAPI
IF "%LT1I%"=="2" GOTO TYPI
IF "%LT1I%"=="3" GOTO CAPI
IF "%LT1I%"=="4" GOTO TYPI
IF "%LT1I%"=="5" GOTO CAPI
IF "%LT1I%"=="6" GOTO TYPI
IF "%LT1I%"=="7" GOTO CAPI
IF "%LT1I%"=="8" GOTO TYPI
IF "%LT1I%"=="9" GOTO CAPI
:CAPI
:CAPA1I
set CAPA1I=%RANDOM:~0,1%
IF "%CAPA1I%"=="0" set PAS1=A
IF "%CAPA1I%"=="1" GOTO CAPA1I
IF "%CAPA1I%"=="2" set PAS1=B
IF "%CAPA1I%"=="3" GOTO CAPA2I
IF "%CAPA1I%"=="4" set PAS1=D
IF "%CAPA1I%"=="5" GOTO CAPA3I
IF "%CAPA1I%"=="6" set PAS1=E
IF "%CAPA1I%"=="7" GOTO CAPA4I
IF "%CAPA1I%"=="8" set PAS1=F
IF "%CAPA1I%"=="9" GOTO CAPA5I
goto LINE11
:CAPA2I
set CAPA2I=%RANDOM:~0,1%
IF "%CAPA2I%"=="0" set PAS1=G
IF "%CAPA2I%"=="1" GOTO CAPA1I
IF "%CAPA2I%"=="2" set PAS1=H
IF "%CAPA2I%"=="3" GOTO CAPA2I
IF "%CAPA2I%"=="4" set PAS1=I
IF "%CAPA2I%"=="5" GOTO CAPA3I
IF "%CAPA2I%"=="6" set PAS1=J
IF "%CAPA2I%"=="7" GOTO CAPA4I
IF "%CAPA2I%"=="8" set PAS1=K
IF "%CAPA2I%"=="9" GOTO CAPA5I
goto LINE11
:CAPA3I
set CAPA3I=%RANDOM:~0,1%
IF "%CAPA3I%"=="0" set PAS1=L
IF "%CAPA3I%"=="1" GOTO CAPA1I
IF "%CAPA3I%"=="2" set PAS1=M
IF "%CAPA3I%"=="3" GOTO CAPA2I
IF "%CAPA3I%"=="4" set PAS1=N
IF "%CAPA3I%"=="5" GOTO CAPA3I
IF "%CAPA3I%"=="6" set PAS1=O
IF "%CAPA3I%"=="7" GOTO CAPA4I
IF "%CAPA3I%"=="8" set PAS1=P
IF "%CAPA3I%"=="9" GOTO CAPA5I
goto LINE11
:CAPA4I
set CAPA4I=%RANDOM:~0,1%
IF "%CAPA4I%"=="0" set PAS1=Q
IF "%CAPA4I%"=="1" GOTO CAPA1I
IF "%CAPA4I%"=="2" set PAS1=R
IF "%CAPA4I%"=="3" GOTO CAPA2I
IF "%CAPA4I%"=="4" set PAS1=S
IF "%CAPA4I%"=="5" GOTO CAPA3I
IF "%CAPA4I%"=="6" set PAS1=T
IF "%CAPA4I%"=="7" GOTO CAPA4I
IF "%CAPA4I%"=="8" set PAS1=U
IF "%CAPA4I%"=="9" GOTO CAPA5I
goto LINE11
:CAPA5I
set CAPA5I=%RANDOM:~0,1%
IF "%CAPA5I%"=="0" set PAS1=V
IF "%CAPA5I%"=="1" GOTO CAPA1I
IF "%CAPA5I%"=="2" set PAS1=W
IF "%CAPA5I%"=="3" GOTO CAPA2I
IF "%CAPA5I%"=="4" set PAS1=X
IF "%CAPA5I%"=="5" GOTO CAPA3I
IF "%CAPA5I%"=="6" set PAS1=Y
IF "%CAPA5I%"=="7" GOTO CAPA4I
IF "%CAPA5I%"=="8" set PAS1=Z
IF "%CAPA5I%"=="9" GOTO CAPA5I
goto LINE11
:TYPI
:TYPA1I
set TYPA1I=%RANDOM:~0,1%
IF "%TYPA1I%"=="0" set PAS1=a
IF "%TYPA1I%"=="1" GOTO TYPA1I
IF "%TYPA1I%"=="2" set PAS1=b
IF "%TYPA1I%"=="3" GOTO TYPA2I
IF "%TYPA1I%"=="4" set PAS1=d
IF "%TYPA1I%"=="5" GOTO TYPA3I
IF "%TYPA1I%"=="6" set PAS1=e
IF "%TYPA1I%"=="7" GOTO TYPA4I
IF "%TYPA1I%"=="8" set PAS1=f
IF "%TYPA1I%"=="9" GOTO TYPA5I
goto LINE11
:TYPA2I
set TYPA2I=%RANDOM:~0,1%
IF "%TYPA2I%"=="0" set PAS1=g
IF "%TYPA2I%"=="1" GOTO TYPA1I
IF "%TYPA2I%"=="2" set PAS1=h
IF "%TYPA2I%"=="3" GOTO TYPA2I
IF "%TYPA2I%"=="4" set PAS1=i
IF "%TYPA2I%"=="5" GOTO TYPA3I
IF "%TYPA2I%"=="6" set PAS1=j
IF "%TYPA2I%"=="7" GOTO TYPA4I
IF "%TYPA2I%"=="8" set PAS1=k
IF "%TYPA2I%"=="9" GOTO TYPA5I
goto LINE11
:TYPA3I
set TYPA3I=%RANDOM:~0,1%
IF "%TYPA3I%"=="0" set PAS1=l
IF "%TYPA3I%"=="1" GOTO TYPA1I
IF "%TYPA3I%"=="2" set PAS1=m
IF "%TYPA3I%"=="3" GOTO TYPA2I
IF "%TYPA3I%"=="4" set PAS1=n
IF "%TYPA3I%"=="5" GOTO TYPA3I
IF "%TYPA3I%"=="6" set PAS1=o
IF "%TYPA3I%"=="7" GOTO TYPA4I
IF "%TYPA3I%"=="8" set PAS1=p
IF "%TYPA3I%"=="9" GOTO TYPA5I
goto LINE11
:TYPA4I
set TYPA4I=%RANDOM:~0,1%
IF "%TYPA4I%"=="0" set PAS1=q
IF "%TYPA4I%"=="1" GOTO TYPA1I
IF "%TYPA4I%"=="2" set PAS1=r
IF "%TYPA4I%"=="3" GOTO TYPA2I
IF "%TYPA4I%"=="4" set PAS1=s
IF "%TYPA4I%"=="5" GOTO TYPA3I
IF "%TYPA4I%"=="6" set PAS1=t
IF "%TYPA4I%"=="7" GOTO TYPA4I
IF "%TYPA4I%"=="8" set PAS1=u
IF "%TYPA4I%"=="9" GOTO TYPA5I
goto LINE11
:TYPA5I
set TYPA5I=%RANDOM:~0,1%
IF "%TYPA5I%"=="0" set PAS1=v
IF "%TYPA5I%"=="1" GOTO TYPA1I
IF "%TYPA5I%"=="2" set PAS1=w
IF "%TYPA5I%"=="3" GOTO TYPA2I
IF "%TYPA5I%"=="4" set PAS1=x
IF "%TYPA5I%"=="5" GOTO TYPA3I
IF "%TYPA5I%"=="6" set PAS1=y
IF "%TYPA5I%"=="7" GOTO TYPA4I
IF "%TYPA5I%"=="8" set PAS1=z
IF "%TYPA5I%"=="9" GOTO TYPA5I
goto LINE11
:LINE11
set STP1J=%RANDOM:~0,1%
IF "%STP1J%"=="0" GOTO NUBR1J
IF "%STP1J%"=="1" GOTO LTRS1J
IF "%STP1J%"=="2" GOTO NUBR1J
IF "%STP1J%"=="3" GOTO LTRS1J
IF "%STP1J%"=="4" GOTO NUBR1J
IF "%STP1J%"=="5" GOTO LTRS1J
IF "%STP1J%"=="6" GOTO NUBR1J
IF "%STP1J%"=="7" GOTO LTRS1J
IF "%STP1J%"=="8" GOTO NUBR1J
IF "%STP1J%"=="9" GOTO LTRS1J
:NUBR1J
set NUBR1J=%RANDOM:~0,1%
set PAS2=%NUBR1J%
goto LINE12
:LTRS1J
set LT1J=%RANDOM:~0,1%
IF "%LT1J%"=="0" GOTO TYPJ
IF "%LT1J%"=="1" GOTO CAPJ
IF "%LT1J%"=="2" GOTO TYPJ
IF "%LT1J%"=="3" GOTO CAPJ
IF "%LT1J%"=="4" GOTO TYPJ
IF "%LT1J%"=="5" GOTO CAPJ
IF "%LT1J%"=="6" GOTO TYPJ
IF "%LT1J%"=="7" GOTO CAPJ
IF "%LT1J%"=="8" GOTO TYPJ
IF "%LT1J%"=="9" GOTO CAPJ
:CAPJ
:CAPA1J
set CAPA1J=%RANDOM:~0,1%
IF "%CAPA1J%"=="0" set PAS2=B
IF "%CAPA1J%"=="1" GOTO CAPA1J
IF "%CAPA1J%"=="2" set PAS2=C
IF "%CAPA1J%"=="3" GOTO CAPA2J
IF "%CAPA1J%"=="4" set PAS2=D
IF "%CAPA1J%"=="5" GOTO CAPA3J
IF "%CAPA1J%"=="6" set PAS2=E
IF "%CAPA1J%"=="7" GOTO CAPA4J
IF "%CAPA1J%"=="8" set PAS2=F
IF "%CAPA1J%"=="9" GOTO CAPA5J
goto LINE12
:CAPA2J
set CAPA2J=%RANDOM:~0,1%
IF "%CAPA2J%"=="0" set PAS2=G
IF "%CAPA2J%"=="1" GOTO CAPA1J
IF "%CAPA2J%"=="2" set PAS2=H
IF "%CAPA2J%"=="3" GOTO CAPA2J
IF "%CAPA2J%"=="4" set PAS2=I
IF "%CAPA2J%"=="5" GOTO CAPA3J
IF "%CAPA2J%"=="6" set PAS2=J
IF "%CAPA2J%"=="7" GOTO CAPA4J
IF "%CAPA2J%"=="8" set PAS2=K
IF "%CAPA2J%"=="9" GOTO CAPA5J
goto LINE12
:CAPA3J
set CAPA3J=%RANDOM:~0,1%
IF "%CAPA3J%"=="0" set PAS2=L
IF "%CAPA3J%"=="1" GOTO CAPA1J
IF "%CAPA3J%"=="2" set PAS2=M
IF "%CAPA3J%"=="3" GOTO CAPA2J
IF "%CAPA3J%"=="4" set PAS2=N
IF "%CAPA3J%"=="5" GOTO CAPA3J
IF "%CAPA3J%"=="6" set PAS2=O
IF "%CAPA3J%"=="7" GOTO CAPA4J
IF "%CAPA3J%"=="8" set PAS2=P
IF "%CAPA3J%"=="9" GOTO CAPA5J
goto LINE12
:CAPA4J
set CAPA4J=%RANDOM:~0,1%
IF "%CAPA4J%"=="0" set PAS2=Q
IF "%CAPA4J%"=="1" GOTO CAPA1J
IF "%CAPA4J%"=="2" set PAS2=R
IF "%CAPA4J%"=="3" GOTO CAPA2J
IF "%CAPA4J%"=="4" set PAS2=S
IF "%CAPA4J%"=="5" GOTO CAPA3J
IF "%CAPA4J%"=="6" set PAS2=T
IF "%CAPA4J%"=="7" GOTO CAPA4J
IF "%CAPA4J%"=="8" set PAS2=U
IF "%CAPA4J%"=="9" GOTO CAPA5J
goto LINE12
:CAPA5J
set CAPA5J=%RANDOM:~0,1%
IF "%CAPA5J%"=="0" set PAS2=V
IF "%CAPA5J%"=="1" GOTO CAPA1J
IF "%CAPA5J%"=="2" set PAS2=W
IF "%CAPA5J%"=="3" GOTO CAPA2J
IF "%CAPA5J%"=="4" set PAS2=X
IF "%CAPA5J%"=="5" GOTO CAPA3J
IF "%CAPA5J%"=="6" set PAS2=Y
IF "%CAPA5J%"=="7" GOTO CAPA4J
IF "%CAPA5J%"=="8" set PAS2=Z
IF "%CAPA5J%"=="9" GOTO CAPA5J
goto LINE12
:TYPJ
:TYPA1J
set TYPA1J=%RANDOM:~0,1%
IF "%TYPA1J%"=="0" set PAS2=b
IF "%TYPA1J%"=="1" GOTO TYPA1J
IF "%TYPA1J%"=="2" set PAS2=c
IF "%TYPA1J%"=="3" GOTO TYPA2J
IF "%TYPA1J%"=="4" set PAS2=d
IF "%TYPA1J%"=="5" GOTO TYPA3J
IF "%TYPA1J%"=="6" set PAS2=e
IF "%TYPA1J%"=="7" GOTO TYPA4J
IF "%TYPA1J%"=="8" set PAS2=f
IF "%TYPA1J%"=="9" GOTO TYPA5J
goto LINE12
:TYPA2J
set TYPA2J=%RANDOM:~0,1%
IF "%TYPA2J%"=="0" set PAS2=g
IF "%TYPA2J%"=="1" GOTO TYPA1J
IF "%TYPA2J%"=="2" set PAS2=h
IF "%TYPA2J%"=="3" GOTO TYPA2J
IF "%TYPA2J%"=="4" set PAS2=i
IF "%TYPA2J%"=="5" GOTO TYPA3J
IF "%TYPA2J%"=="6" set PAS2=j
IF "%TYPA2J%"=="7" GOTO TYPA4J
IF "%TYPA2J%"=="8" set PAS2=k
IF "%TYPA2J%"=="9" GOTO TYPA5J
goto LINE12
:TYPA3J
set TYPA3J=%RANDOM:~0,1%
IF "%TYPA3J%"=="0" set PAS2=l
IF "%TYPA3J%"=="1" GOTO TYPA1J
IF "%TYPA3J%"=="2" set PAS2=m
IF "%TYPA3J%"=="3" GOTO TYPA2J
IF "%TYPA3J%"=="4" set PAS2=n
IF "%TYPA3J%"=="5" GOTO TYPA3J
IF "%TYPA3J%"=="6" set PAS2=o
IF "%TYPA3J%"=="7" GOTO TYPA4J
IF "%TYPA3J%"=="8" set PAS2=p
IF "%TYPA3J%"=="9" GOTO TYPA5J
goto LINE12
:TYPA4J
set TYPA4J=%RANDOM:~0,1%
IF "%TYPA4J%"=="0" set PAS2=q
IF "%TYPA4J%"=="1" GOTO TYPA1J
IF "%TYPA4J%"=="2" set PAS2=r
IF "%TYPA4J%"=="3" GOTO TYPA2J
IF "%TYPA4J%"=="4" set PAS2=s
IF "%TYPA4J%"=="5" GOTO TYPA3J
IF "%TYPA4J%"=="6" set PAS2=t
IF "%TYPA4J%"=="7" GOTO TYPA4J
IF "%TYPA4J%"=="8" set PAS2=u
IF "%TYPA4J%"=="9" GOTO TYPA5J
goto LINE12
:TYPA5J
set TYPA5J=%RANDOM:~0,1%
IF "%TYPA5J%"=="0" set PAS2=v
IF "%TYPA5J%"=="1" GOTO TYPA1J
IF "%TYPA5J%"=="2" set PAS2=w
IF "%TYPA5J%"=="3" GOTO TYPA2J
IF "%TYPA5J%"=="4" set PAS2=x
IF "%TYPA5J%"=="5" GOTO TYPA3J
IF "%TYPA5J%"=="6" set PAS2=y
IF "%TYPA5J%"=="7" GOTO TYPA4J
IF "%TYPA5J%"=="8" set PAS2=z
IF "%TYPA5J%"=="9" GOTO TYPA5J
goto LINE12
:LINE12
set STP1K=%RANDOM:~0,1%
IF "%STP1K%"=="0" GOTO NUBR1K
IF "%STP1K%"=="1" GOTO LTRS1K
IF "%STP1K%"=="2" GOTO NUBR1K
IF "%STP1K%"=="3" GOTO LTRS1K
IF "%STP1K%"=="4" GOTO NUBR1K
IF "%STP1K%"=="5" GOTO LTRS1K
IF "%STP1K%"=="6" GOTO NUBR1K
IF "%STP1K%"=="7" GOTO LTRS1K
IF "%STP1K%"=="8" GOTO NUBR1K
IF "%STP1K%"=="9" GOTO LTRS1K
:NUBR1K
set NUBR1K=%RANDOM:~0,1%
set PAS3=%NUBR1K%
goto LINE13
:LTRS1K
set LT1K=%RANDOM:~0,1%
IF "%LT1K%"=="0" GOTO TYPK
IF "%LT1K%"=="1" GOTO CAPK
IF "%LT1K%"=="2" GOTO TYPK
IF "%LT1K%"=="3" GOTO CAPK
IF "%LT1K%"=="4" GOTO TYPK
IF "%LT1K%"=="5" GOTO CAPK
IF "%LT1K%"=="6" GOTO TYPK
IF "%LT1K%"=="7" GOTO CAPK
IF "%LT1K%"=="8" GOTO TYPK
IF "%LT1K%"=="9" GOTO CAPK
:CAPK
:CAPA1K
set CAPA1K=%RANDOM:~0,1%
IF "%CAPA1K%"=="0" set PAS3=A
IF "%CAPA1K%"=="1" GOTO CAPA1K
IF "%CAPA1K%"=="2" set PAS3=B
IF "%CAPA1K%"=="3" GOTO CAPA2K
IF "%CAPA1K%"=="4" set PAS3=C
IF "%CAPA1K%"=="5" GOTO CAPA3K
IF "%CAPA1K%"=="6" set PAS3=D
IF "%CAPA1K%"=="7" GOTO CAPA4K
IF "%CAPA1K%"=="8" set PAS3=E
IF "%CAPA1K%"=="9" GOTO CAPA5K
goto LINE13
:CAPA2K
set CAPA2K=%RANDOM:~0,1%
IF "%CAPA2K%"=="0" set PAS3=F
IF "%CAPA2K%"=="1" GOTO CAPA1K
IF "%CAPA2K%"=="2" set PAS3=G
IF "%CAPA2K%"=="3" GOTO CAPA2K
IF "%CAPA2K%"=="4" set PAS3=H
IF "%CAPA2K%"=="5" GOTO CAPA3K
IF "%CAPA2K%"=="6" set PAS3=I
IF "%CAPA2K%"=="7" GOTO CAPA4K
IF "%CAPA2K%"=="8" set PAS3=J
IF "%CAPA2K%"=="9" GOTO CAPA5K
goto LINE13
:CAPA3K
set CAPA3K=%RANDOM:~0,1%
IF "%CAPA3K%"=="0" set PAS3=K
IF "%CAPA3K%"=="1" GOTO CAPA1K
IF "%CAPA3K%"=="2" set PAS3=L
IF "%CAPA3K%"=="3" GOTO CAPA2K
IF "%CAPA3K%"=="4" set PAS3=M
IF "%CAPA3K%"=="5" GOTO CAPA3K
IF "%CAPA3K%"=="6" set PAS3=N
IF "%CAPA3K%"=="7" GOTO CAPA4K
IF "%CAPA3K%"=="8" set PAS3=O
IF "%CAPA3K%"=="9" GOTO CAPA5K
goto LINE13
:CAPA4K
set CAPA4K=%RANDOM:~0,1%
IF "%CAPA4K%"=="0" set PAS3=P
IF "%CAPA4K%"=="1" GOTO CAPA1K
IF "%CAPA4K%"=="2" set PAS3=Q
IF "%CAPA4K%"=="3" GOTO CAPA2K
IF "%CAPA4K%"=="4" set PAS3=R
IF "%CAPA4K%"=="5" GOTO CAPA3K
IF "%CAPA4K%"=="6" set PAS3=S
IF "%CAPA4K%"=="7" GOTO CAPA4K
IF "%CAPA4K%"=="8" set PAS3=U
IF "%CAPA4K%"=="9" GOTO CAPA5K
goto LINE13
:CAPA5K
set CAPA5K=%RANDOM:~0,1%
IF "%CAPA5K%"=="0" set PAS3=V
IF "%CAPA5K%"=="1" GOTO CAPA1K
IF "%CAPA5K%"=="2" set PAS3=W
IF "%CAPA5K%"=="3" GOTO CAPA2K
IF "%CAPA5K%"=="4" set PAS3=X
IF "%CAPA5K%"=="5" GOTO CAPA3K
IF "%CAPA5K%"=="6" set PAS3=Y
IF "%CAPA5K%"=="7" GOTO CAPA4K
IF "%CAPA5K%"=="8" set PAS3=Z
IF "%CAPA5K%"=="9" GOTO CAPA5K
goto LINE13
:TYPK
:TYPA1K
set TYPA1K=%RANDOM:~0,1%
IF "%TYPA1K%"=="0" set PAS3=a
IF "%TYPA1K%"=="1" GOTO TYPA1K
IF "%TYPA1K%"=="2" set PAS3=b
IF "%TYPA1K%"=="3" GOTO TYPA2K
IF "%TYPA1K%"=="4" set PAS3=c
IF "%TYPA1K%"=="5" GOTO TYPA3K
IF "%TYPA1K%"=="6" set PAS3=d
IF "%TYPA1K%"=="7" GOTO TYPA4K
IF "%TYPA1K%"=="8" set PAS3=e
IF "%TYPA1K%"=="9" GOTO TYPA5K
goto LINE13
:TYPA2K
set TYPA2K=%RANDOM:~0,1%
IF "%TYPA2K%"=="0" set PAS3=f
IF "%TYPA2K%"=="1" GOTO TYPA1K
IF "%TYPA2K%"=="2" set PAS3=g
IF "%TYPA2K%"=="3" GOTO TYPA2K
IF "%TYPA2K%"=="4" set PAS3=h
IF "%TYPA2K%"=="5" GOTO TYPA3K
IF "%TYPA2K%"=="6" set PAS3=i
IF "%TYPA2K%"=="7" GOTO TYPA4K
IF "%TYPA2K%"=="8" set PAS3=j
IF "%TYPA2K%"=="9" GOTO TYPA5K
goto LINE13
:TYPA3K
set TYPA3K=%RANDOM:~0,1%
IF "%TYPA3K%"=="0" set PAS3=k
IF "%TYPA3K%"=="1" GOTO TYPA1K
IF "%TYPA3K%"=="2" set PAS3=l
IF "%TYPA3K%"=="3" GOTO TYPA2K
IF "%TYPA3K%"=="4" set PAS3=m
IF "%TYPA3K%"=="5" GOTO TYPA3K
IF "%TYPA3K%"=="6" set PAS3=n
IF "%TYPA3K%"=="7" GOTO TYPA4K
IF "%TYPA3K%"=="8" set PAS3=o
IF "%TYPA3K%"=="9" GOTO TYPA5K
goto LINE13
:TYPA4K
set TYPA4K=%RANDOM:~0,1%
IF "%TYPA4K%"=="0" set PAS3=p
IF "%TYPA4K%"=="1" GOTO TYPA1K
IF "%TYPA4K%"=="2" set PAS3=q
IF "%TYPA4K%"=="3" GOTO TYPA2K
IF "%TYPA4K%"=="4" set PAS3=r
IF "%TYPA4K%"=="5" GOTO TYPA3K
IF "%TYPA4K%"=="6" set PAS3=s
IF "%TYPA4K%"=="7" GOTO TYPA4K
IF "%TYPA4K%"=="8" set PAS3=u
IF "%TYPA4K%"=="9" GOTO TYPA5K
goto LINE13
:TYPA5K
set TYPA5K=%RANDOM:~0,1%
IF "%TYPA5K%"=="0" set PAS3=v
IF "%TYPA5K%"=="1" GOTO TYPA1K
IF "%TYPA5K%"=="2" set PAS3=w
IF "%TYPA5K%"=="3" GOTO TYPA2K
IF "%TYPA5K%"=="4" set PAS3=x
IF "%TYPA5K%"=="5" GOTO TYPA3K
IF "%TYPA5K%"=="6" set PAS3=y
IF "%TYPA5K%"=="7" GOTO TYPA4K
IF "%TYPA5K%"=="8" set PAS3=z
IF "%TYPA5K%"=="9" GOTO TYPA5K
goto LINE13
:LINE13
set STP1L=%RANDOM:~0,1%
IF "%STP1L%"=="0" GOTO NUBR1L
IF "%STP1L%"=="1" GOTO LTRS1L
IF "%STP1L%"=="2" GOTO NUBR1L
IF "%STP1L%"=="3" GOTO LTRS1L
IF "%STP1L%"=="4" GOTO NUBR1L
IF "%STP1L%"=="5" GOTO LTRS1L
IF "%STP1L%"=="6" GOTO NUBR1L
IF "%STP1L%"=="7" GOTO LTRS1L
IF "%STP1L%"=="8" GOTO NUBR1L
IF "%STP1L%"=="9" GOTO LTRS1L
:NUBR1L
set NUBR1L=%RANDOM:~0,1%
set PAS4=%NUBR1L%
goto LINE14
:LTRS1L
set LT1L=%RANDOM:~0,1%
IF "%LT1L%"=="0" GOTO TYPL
IF "%LT1L%"=="1" GOTO CAPL
IF "%LT1L%"=="2" GOTO TYPL
IF "%LT1L%"=="3" GOTO CAPL
IF "%LT1L%"=="4" GOTO TYPL
IF "%LT1L%"=="5" GOTO CAPL
IF "%LT1L%"=="6" GOTO TYPL
IF "%LT1L%"=="7" GOTO CAPL
IF "%LT1L%"=="8" GOTO TYPL
IF "%LT1L%"=="9" GOTO CAPL
:CAPL
:CAPA1L
set CAPA1L=%RANDOM:~0,1%
IF "%CAPA1L%"=="0" set PAS4=A
IF "%CAPA1L%"=="1" GOTO CAPA1L
IF "%CAPA1L%"=="2" set PAS4=B
IF "%CAPA1L%"=="3" GOTO CAPA2L
IF "%CAPA1L%"=="4" set PAS4=C
IF "%CAPA1L%"=="5" GOTO CAPA3L
IF "%CAPA1L%"=="6" set PAS4=D
IF "%CAPA1L%"=="7" GOTO CAPA4L
IF "%CAPA1L%"=="8" set PAS4=E
IF "%CAPA1L%"=="9" GOTO CAPA5L
goto LINE14
:CAPA2L
set CAPA2L=%RANDOM:~0,1%
IF "%CAPA2L%"=="0" set PAS4=F
IF "%CAPA2L%"=="1" GOTO CAPA1L
IF "%CAPA2L%"=="2" set PAS4=G
IF "%CAPA2L%"=="3" GOTO CAPA2L
IF "%CAPA2L%"=="4" set PAS4=H
IF "%CAPA2L%"=="5" GOTO CAPA3L
IF "%CAPA2L%"=="6" set PAS4=I
IF "%CAPA2L%"=="7" GOTO CAPA4L
IF "%CAPA2L%"=="8" set PAS4=J
IF "%CAPA2L%"=="9" GOTO CAPA5L
goto LINE14
:CAPA3L
set CAPA3L=%RANDOM:~0,1%
IF "%CAPA3L%"=="0" set PAS4=K
IF "%CAPA3L%"=="1" GOTO CAPA1L
IF "%CAPA3L%"=="2" set PAS4=L
IF "%CAPA3L%"=="3" GOTO CAPA2L
IF "%CAPA3L%"=="4" set PAS4=M
IF "%CAPA3L%"=="5" GOTO CAPA3L
IF "%CAPA3L%"=="6" set PAS4=N
IF "%CAPA3L%"=="7" GOTO CAPA4L
IF "%CAPA3L%"=="8" set PAS4=O
IF "%CAPA3L%"=="9" GOTO CAPA5L
goto LINE14
:CAPA4L
set CAPA4L=%RANDOM:~0,1%
IF "%CAPA4L%"=="0" set PAS4=P
IF "%CAPA4L%"=="1" GOTO CAPA1L
IF "%CAPA4L%"=="2" set PAS4=Q
IF "%CAPA4L%"=="3" GOTO CAPA2L
IF "%CAPA4L%"=="4" set PAS4=R
IF "%CAPA4L%"=="5" GOTO CAPA3L
IF "%CAPA4L%"=="6" set PAS4=S
IF "%CAPA4L%"=="7" GOTO CAPA4L
IF "%CAPA4L%"=="8" set PAS4=U
IF "%CAPA4L%"=="9" GOTO CAPA5L
goto LINE14
:CAPA5L
set CAPA5L=%RANDOM:~0,1%
IF "%CAPA5L%"=="0" set PAS4=V
IF "%CAPA5L%"=="1" GOTO CAPA1L
IF "%CAPA5L%"=="2" set PAS4=W
IF "%CAPA5L%"=="3" GOTO CAPA2L
IF "%CAPA5L%"=="4" set PAS4=X
IF "%CAPA5L%"=="5" GOTO CAPA3L
IF "%CAPA5L%"=="6" set PAS4=Y
IF "%CAPA5L%"=="7" GOTO CAPA4L
IF "%CAPA5L%"=="8" set PAS4=Z
IF "%CAPA5L%"=="9" GOTO CAPA5L
goto LINE14
:TYPL
:TYPA1L
set TYPA1L=%RANDOM:~0,1%
IF "%TYPA1L%"=="0" set PAS4=a
IF "%TYPA1L%"=="1" GOTO TYPA1L
IF "%TYPA1L%"=="2" set PAS4=b
IF "%TYPA1L%"=="3" GOTO TYPA2L
IF "%TYPA1L%"=="4" set PAS4=c
IF "%TYPA1L%"=="5" GOTO TYPA3L
IF "%TYPA1L%"=="6" set PAS4=d
IF "%TYPA1L%"=="7" GOTO TYPA4L
IF "%TYPA1L%"=="8" set PAS4=e
IF "%TYPA1L%"=="9" GOTO TYPA5L
goto LINE14
:TYPA2L
set TYPA2L=%RANDOM:~0,1%
IF "%TYPA2L%"=="0" set PAS4=f
IF "%TYPA2L%"=="1" GOTO TYPA1L
IF "%TYPA2L%"=="2" set PAS4=g
IF "%TYPA2L%"=="3" GOTO TYPA2L
IF "%TYPA2L%"=="4" set PAS4=h
IF "%TYPA2L%"=="5" GOTO TYPA3L
IF "%TYPA2L%"=="6" set PAS4=i
IF "%TYPA2L%"=="7" GOTO TYPA4L
IF "%TYPA2L%"=="8" set PAS4=j
IF "%TYPA2L%"=="9" GOTO TYPA5L
goto LINE14
:TYPA3L
set TYPA3L=%RANDOM:~0,1%
IF "%TYPA3L%"=="0" set PAS4=k
IF "%TYPA3L%"=="1" GOTO TYPA1L
IF "%TYPA3L%"=="2" set PAS4=l
IF "%TYPA3L%"=="3" GOTO TYPA2L
IF "%TYPA3L%"=="4" set PAS4=m
IF "%TYPA3L%"=="5" GOTO TYPA3L
IF "%TYPA3L%"=="6" set PAS4=n
IF "%TYPA3L%"=="7" GOTO TYPA4L
IF "%TYPA3L%"=="8" set PAS4=o
IF "%TYPA3L%"=="9" GOTO TYPA5L
goto LINE14
:TYPA4L
set TYPA4L=%RANDOM:~0,1%
IF "%TYPA4L%"=="0" set PAS4=p
IF "%TYPA4L%"=="1" GOTO TYPA1L
IF "%TYPA4L%"=="2" set PAS4=q
IF "%TYPA4L%"=="3" GOTO TYPA2L
IF "%TYPA4L%"=="4" set PAS4=r
IF "%TYPA4L%"=="5" GOTO TYPA3L
IF "%TYPA4L%"=="6" set PAS4=s
IF "%TYPA4L%"=="7" GOTO TYPA4L
IF "%TYPA4L%"=="8" set PAS4=u
IF "%TYPA4L%"=="9" GOTO TYPA5L
goto LINE14
:TYPA5L
set TYPA5L=%RANDOM:~0,1%
IF "%TYPA5L%"=="0" set PAS4=v
IF "%TYPA5L%"=="1" GOTO TYPA1L
IF "%TYPA5L%"=="2" set PAS4=w
IF "%TYPA5L%"=="3" GOTO TYPA2L
IF "%TYPA5L%"=="4" set PAS4=x
IF "%TYPA5L%"=="5" GOTO TYPA3L
IF "%TYPA5L%"=="6" set PAS4=y
IF "%TYPA5L%"=="7" GOTO TYPA4L
IF "%TYPA5L%"=="8" set PAS4=z
IF "%TYPA5L%"=="9" GOTO TYPA5L
goto LINE14
:LINE14
set STP1M=%RANDOM:~0,1%
IF "%STP1M%"=="0" GOTO NUBR1M
IF "%STP1M%"=="1" GOTO LTRS1M
IF "%STP1M%"=="2" GOTO NUBR1M
IF "%STP1M%"=="3" GOTO LTRS1M
IF "%STP1M%"=="4" GOTO NUBR1M
IF "%STP1M%"=="5" GOTO LTRS1M
IF "%STP1M%"=="6" GOTO NUBR1M
IF "%STP1M%"=="7" GOTO LTRS1M
IF "%STP1M%"=="8" GOTO NUBR1M
IF "%STP1M%"=="9" GOTO LTRS1M
:NUBR1M
set NUBR1M=%RANDOM:~0,1%
set PAS5=%NUBR1M%
goto LINE15
:LTRS1M
set LT1M=%RANDOM:~0,1%
IF "%LT1M%"=="0" GOTO TYPM
IF "%LT1M%"=="1" GOTO CAPM
IF "%LT1M%"=="2" GOTO TYPM
IF "%LT1M%"=="3" GOTO CAPM
IF "%LT1M%"=="4" GOTO TYPM
IF "%LT1M%"=="5" GOTO CAPM
IF "%LT1M%"=="6" GOTO TYPM
IF "%LT1M%"=="7" GOTO CAPM
IF "%LT1M%"=="8" GOTO TYPM
IF "%LT1M%"=="9" GOTO CAPM
:CAPM
:CAPA1M
set CAPA1M=%RANDOM:~0,1%
IF "%CAPA1M%"=="0" set PAS5=A
IF "%CAPA1M%"=="1" GOTO CAPA1M
IF "%CAPA1M%"=="2" set PAS5=B
IF "%CAPA1M%"=="3" GOTO CAPA2M
IF "%CAPA1M%"=="4" set PAS5=C
IF "%CAPA1M%"=="5" GOTO CAPA3M
IF "%CAPA1M%"=="6" set PAS5=D
IF "%CAPA1M%"=="7" GOTO CAPA4M
IF "%CAPA1M%"=="8" set PAS5=E
IF "%CAPA1M%"=="9" GOTO CAPA5M
goto LINE15
:CAPA2M
set CAPA2M=%RANDOM:~0,1%
IF "%CAPA2M%"=="0" set PAS5=F
IF "%CAPA2M%"=="1" GOTO CAPA1M
IF "%CAPA2M%"=="2" set PAS5=G
IF "%CAPA2M%"=="3" GOTO CAPA2M
IF "%CAPA2M%"=="4" set PAS5=H
IF "%CAPA2M%"=="5" GOTO CAPA3M
IF "%CAPA2M%"=="6" set PAS5=I
IF "%CAPA2M%"=="7" GOTO CAPA4M
IF "%CAPA2M%"=="8" set PAS5=J
IF "%CAPA2M%"=="9" GOTO CAPA5M
goto LINE15
:CAPA3M
set CAPA3M=%RANDOM:~0,1%
IF "%CAPA3M%"=="0" set PAS5=K
IF "%CAPA3M%"=="1" GOTO CAPA1M
IF "%CAPA3M%"=="2" set PAS5=L
IF "%CAPA3M%"=="3" GOTO CAPA2M
IF "%CAPA3M%"=="4" set PAS5=M
IF "%CAPA3M%"=="5" GOTO CAPA3M
IF "%CAPA3M%"=="6" set PAS5=N
IF "%CAPA3M%"=="7" GOTO CAPA4M
IF "%CAPA3M%"=="8" set PAS5=O
IF "%CAPA3M%"=="9" GOTO CAPA5M
goto LINE15
:CAPA4M
set CAPA4M=%RANDOM:~0,1%
IF "%CAPA4M%"=="0" set PAS5=P
IF "%CAPA4M%"=="1" GOTO CAPA1M
IF "%CAPA4M%"=="2" set PAS5=Q
IF "%CAPA4M%"=="3" GOTO CAPA2M
IF "%CAPA4M%"=="4" set PAS5=R
IF "%CAPA4M%"=="5" GOTO CAPA3M
IF "%CAPA4M%"=="6" set PAS5=S
IF "%CAPA4M%"=="7" GOTO CAPA4M
IF "%CAPA4M%"=="8" set PAS5=U
IF "%CAPA4M%"=="9" GOTO CAPA5M
goto LINE15
:CAPA5M
set CAPA5M=%RANDOM:~0,1%
IF "%CAPA5M%"=="0" set PAS5=V
IF "%CAPA5M%"=="1" GOTO CAPA1M
IF "%CAPA5M%"=="2" set PAS5=W
IF "%CAPA5M%"=="3" GOTO CAPA2M
IF "%CAPA5M%"=="4" set PAS5=X
IF "%CAPA5M%"=="5" GOTO CAPA3M
IF "%CAPA5M%"=="6" set PAS5=Y
IF "%CAPA5M%"=="7" GOTO CAPA4M
IF "%CAPA5M%"=="8" set PAS5=Z
IF "%CAPA5M%"=="9" GOTO CAPA5M
goto LINE15
:TYPM
:TYPA1M
set TYPA1M=%RANDOM:~0,1%
IF "%TYPA1M%"=="0" set PAS5=a
IF "%TYPA1M%"=="1" GOTO TYPA1M
IF "%TYPA1M%"=="2" set PAS5=b
IF "%TYPA1M%"=="3" GOTO TYPA2M
IF "%TYPA1M%"=="4" set PAS5=c
IF "%TYPA1M%"=="5" GOTO TYPA3M
IF "%TYPA1M%"=="6" set PAS5=d
IF "%TYPA1M%"=="7" GOTO TYPA4M
IF "%TYPA1M%"=="8" set PAS5=e
IF "%TYPA1M%"=="9" GOTO TYPA5M
goto LINE15
:TYPA2M
set TYPA2M=%RANDOM:~0,1%
IF "%TYPA2M%"=="0" set PAS5=f
IF "%TYPA2M%"=="1" GOTO TYPA1M
IF "%TYPA2M%"=="2" set PAS5=g
IF "%TYPA2M%"=="3" GOTO TYPA2M
IF "%TYPA2M%"=="4" set PAS5=h
IF "%TYPA2M%"=="5" GOTO TYPA3M
IF "%TYPA2M%"=="6" set PAS5=i
IF "%TYPA2M%"=="7" GOTO TYPA4M
IF "%TYPA2M%"=="8" set PAS5=j
IF "%TYPA2M%"=="9" GOTO TYPA5M
goto LINE15
:TYPA3M
set TYPA3M=%RANDOM:~0,1%
IF "%TYPA3M%"=="0" set PAS5=k
IF "%TYPA3M%"=="1" GOTO TYPA1M
IF "%TYPA3M%"=="2" set PAS5=l
IF "%TYPA3M%"=="3" GOTO TYPA2M
IF "%TYPA3M%"=="4" set PAS5=m
IF "%TYPA3M%"=="5" GOTO TYPA3M
IF "%TYPA3M%"=="6" set PAS5=n
IF "%TYPA3M%"=="7" GOTO TYPA4M
IF "%TYPA3M%"=="8" set PAS5=o
IF "%TYPA3M%"=="9" GOTO TYPA5M
goto LINE15
:TYPA4M
set TYPA4M=%RANDOM:~0,1%
IF "%TYPA4M%"=="0" set PAS5=p
IF "%TYPA4M%"=="1" GOTO TYPA1M
IF "%TYPA4M%"=="2" set PAS5=q
IF "%TYPA4M%"=="3" GOTO TYPA2M
IF "%TYPA4M%"=="4" set PAS5=r
IF "%TYPA4M%"=="5" GOTO TYPA3M
IF "%TYPA4M%"=="6" set PAS5=s
IF "%TYPA4M%"=="7" GOTO TYPA4M
IF "%TYPA4M%"=="8" set PAS5=u
IF "%TYPA4M%"=="9" GOTO TYPA5M
goto LINE15
:TYPA5M
set TYPA5M=%RANDOM:~0,1%
IF "%TYPA5M%"=="0" set PAS5=v
IF "%TYPA5M%"=="1" GOTO TYPA1M
IF "%TYPA5M%"=="2" set PAS5=w
IF "%TYPA5M%"=="3" GOTO TYPA2M
IF "%TYPA5M%"=="4" set PAS5=x
IF "%TYPA5M%"=="5" GOTO TYPA3M
IF "%TYPA5M%"=="6" set PAS5=y
IF "%TYPA5M%"=="7" GOTO TYPA4M
IF "%TYPA5M%"=="8" set PAS5=z
IF "%TYPA5M%"=="9" GOTO TYPA5M
goto LINE15
:LINE15
set STP1N=%RANDOM:~0,1%
IF "%STP1N%"=="0" GOTO NUBR1N
IF "%STP1N%"=="1" GOTO LTRS1N
IF "%STP1N%"=="2" GOTO NUBR1N
IF "%STP1N%"=="3" GOTO LTRS1N
IF "%STP1N%"=="4" GOTO NUBR1N
IF "%STP1N%"=="5" GOTO LTRS1N
IF "%STP1N%"=="6" GOTO NUBR1N
IF "%STP1N%"=="7" GOTO LTRS1N
IF "%STP1N%"=="8" GOTO NUBR1N
IF "%STP1N%"=="9" GOTO LTRS1N
:NUBR1N
set NUBR1N=%RANDOM:~0,1%
set PAS6=%NUBR1N%
goto LINE16
:LTRS1N
set LT1N=%RANDOM:~0,1%
IF "%LT1N%"=="0" GOTO TYPN
IF "%LT1N%"=="1" GOTO CAPN
IF "%LT1N%"=="2" GOTO TYPN
IF "%LT1N%"=="3" GOTO CAPN
IF "%LT1N%"=="4" GOTO TYPN
IF "%LT1N%"=="5" GOTO CAPN
IF "%LT1N%"=="6" GOTO TYPN
IF "%LT1N%"=="7" GOTO CAPN
IF "%LT1N%"=="8" GOTO TYPN
IF "%LT1N%"=="9" GOTO CAPN
:CAPN
:CAPA1N
set CAPA1N=%RANDOM:~0,1%
IF "%CAPA1N%"=="0" set PAS6=A
IF "%CAPA1N%"=="1" GOTO CAPA1N
IF "%CAPA1N%"=="2" set PAS6=B
IF "%CAPA1N%"=="3" GOTO CAPA2N
IF "%CAPA1N%"=="4" set PAS6=C
IF "%CAPA1N%"=="5" GOTO CAPA3N
IF "%CAPA1N%"=="6" set PAS6=D
IF "%CAPA1N%"=="7" GOTO CAPA4N
IF "%CAPA1N%"=="8" set PAS6=E
IF "%CAPA1N%"=="9" GOTO CAPA5N
goto LINE16
:CAPA2N
set CAPA2N=%RANDOM:~0,1%
IF "%CAPA2N%"=="0" set PAS6=F
IF "%CAPA2N%"=="1" GOTO CAPA1N
IF "%CAPA2N%"=="2" set PAS6=G
IF "%CAPA2N%"=="3" GOTO CAPA2N
IF "%CAPA2N%"=="4" set PAS6=H
IF "%CAPA2N%"=="5" GOTO CAPA3N
IF "%CAPA2N%"=="6" set PAS6=I
IF "%CAPA2N%"=="7" GOTO CAPA4N
IF "%CAPA2N%"=="8" set PAS6=J
IF "%CAPA2N%"=="9" GOTO CAPA5N
goto LINE16
:CAPA3N
set CAPA3N=%RANDOM:~0,1%
IF "%CAPA3N%"=="0" set PAS6=K
IF "%CAPA3N%"=="1" GOTO CAPA1N
IF "%CAPA3N%"=="2" set PAS6=L
IF "%CAPA3N%"=="3" GOTO CAPA2N
IF "%CAPA3N%"=="4" set PAS6=M
IF "%CAPA3N%"=="5" GOTO CAPA3N
IF "%CAPA3N%"=="6" set PAS6=N
IF "%CAPA3N%"=="7" GOTO CAPA4N
IF "%CAPA3N%"=="8" set PAS6=O
IF "%CAPA3N%"=="9" GOTO CAPA5N
goto LINE16
:CAPA4N
set CAPA4N=%RANDOM:~0,1%
IF "%CAPA4N%"=="0" set PAS6=P
IF "%CAPA4N%"=="1" GOTO CAPA1N
IF "%CAPA4N%"=="2" set PAS6=Q
IF "%CAPA4N%"=="3" GOTO CAPA2N
IF "%CAPA4N%"=="4" set PAS6=R
IF "%CAPA4N%"=="5" GOTO CAPA3N
IF "%CAPA4N%"=="6" set PAS6=S
IF "%CAPA4N%"=="7" GOTO CAPA4N
IF "%CAPA4N%"=="8" set PAS6=U
IF "%CAPA4N%"=="9" GOTO CAPA5N
goto LINE16
:CAPA5N
set CAPA5N=%RANDOM:~0,1%
IF "%CAPA5N%"=="0" set PAS6=V
IF "%CAPA5N%"=="1" GOTO CAPA1N
IF "%CAPA5N%"=="2" set PAS6=W
IF "%CAPA5N%"=="3" GOTO CAPA2N
IF "%CAPA5N%"=="4" set PAS6=X
IF "%CAPA5N%"=="5" GOTO CAPA3N
IF "%CAPA5N%"=="6" set PAS6=Y
IF "%CAPA5N%"=="7" GOTO CAPA4N
IF "%CAPA5N%"=="8" set PAS6=Z
IF "%CAPA5N%"=="9" GOTO CAPA5N
goto LINE16
:TYPN
:TYPA1N
set TYPA1N=%RANDOM:~0,1%
IF "%TYPA1N%"=="0" set PAS6=a
IF "%TYPA1N%"=="1" GOTO TYPA1N
IF "%TYPA1N%"=="2" set PAS6=b
IF "%TYPA1N%"=="3" GOTO TYPA2N
IF "%TYPA1N%"=="4" set PAS6=c
IF "%TYPA1N%"=="5" GOTO TYPA3N
IF "%TYPA1N%"=="6" set PAS6=d
IF "%TYPA1N%"=="7" GOTO TYPA4N
IF "%TYPA1N%"=="8" set PAS6=e
IF "%TYPA1N%"=="9" GOTO TYPA5N
goto LINE16
:TYPA2N
set TYPA2N=%RANDOM:~0,1%
IF "%TYPA2N%"=="0" set PAS6=f
IF "%TYPA2N%"=="1" GOTO TYPA1N
IF "%TYPA2N%"=="2" set PAS6=g
IF "%TYPA2N%"=="3" GOTO TYPA2N
IF "%TYPA2N%"=="4" set PAS6=h
IF "%TYPA2N%"=="5" GOTO TYPA3N
IF "%TYPA2N%"=="6" set PAS6=i
IF "%TYPA2N%"=="7" GOTO TYPA4N
IF "%TYPA2N%"=="8" set PAS6=j
IF "%TYPA2N%"=="9" GOTO TYPA5N
goto LINE16
:TYPA3N
set TYPA3N=%RANDOM:~0,1%
IF "%TYPA3N%"=="0" set PAS6=k
IF "%TYPA3N%"=="1" GOTO TYPA1N
IF "%TYPA3N%"=="2" set PAS6=l
IF "%TYPA3N%"=="3" GOTO TYPA2N
IF "%TYPA3N%"=="4" set PAS6=m
IF "%TYPA3N%"=="5" GOTO TYPA3N
IF "%TYPA3N%"=="6" set PAS6=n
IF "%TYPA3N%"=="7" GOTO TYPA4N
IF "%TYPA3N%"=="8" set PAS6=o
IF "%TYPA3N%"=="9" GOTO TYPA5N
goto LINE16
:TYPA4N
set TYPA4N=%RANDOM:~0,1%
IF "%TYPA4N%"=="0" set PAS6=p
IF "%TYPA4N%"=="1" GOTO TYPA1N
IF "%TYPA4N%"=="2" set PAS6=q
IF "%TYPA4N%"=="3" GOTO TYPA2N
IF "%TYPA4N%"=="4" set PAS6=r
IF "%TYPA4N%"=="5" GOTO TYPA3N
IF "%TYPA4N%"=="6" set PAS6=s
IF "%TYPA4N%"=="7" GOTO TYPA4N
IF "%TYPA4N%"=="8" set PAS6=u
IF "%TYPA4N%"=="9" GOTO TYPA5N
goto LINE16
:TYPA5N
set TYPA5N=%RANDOM:~0,1%
IF "%TYPA5N%"=="0" set PAS6=v
IF "%TYPA5N%"=="1" GOTO TYPA1N
IF "%TYPA5N%"=="2" set PAS6=w
IF "%TYPA5N%"=="3" GOTO TYPA2N
IF "%TYPA5N%"=="4" set PAS6=x
IF "%TYPA5N%"=="5" GOTO TYPA3N
IF "%TYPA5N%"=="6" set PAS6=y
IF "%TYPA5N%"=="7" GOTO TYPA4N
IF "%TYPA5N%"=="8" set PAS6=z
IF "%TYPA5N%"=="9" GOTO TYPA5N
goto LINE16
:LINE16
set STP1O=%RANDOM:~0,1%
IF "%STP1O%"=="0" GOTO NUBR1O
IF "%STP1O%"=="1" GOTO LTRS1O
IF "%STP1O%"=="2" GOTO NUBR1O
IF "%STP1O%"=="3" GOTO LTRS1O
IF "%STP1O%"=="4" GOTO NUBR1O
IF "%STP1O%"=="5" GOTO LTRS1O
IF "%STP1O%"=="6" GOTO NUBR1O
IF "%STP1O%"=="7" GOTO LTRS1O
IF "%STP1O%"=="8" GOTO NUBR1O
IF "%STP1O%"=="9" GOTO LTRS1O
:NUBR1O
set NUBR1O=%RANDOM:~0,1%
set PAS7=%NUBR1O%
goto LINE17
:LTRS1O
set LT1O=%RANDOM:~0,1%
IF "%LT1O%"=="0" GOTO TYPO
IF "%LT1O%"=="1" GOTO CAPO
IF "%LT1O%"=="2" GOTO TYPO
IF "%LT1O%"=="3" GOTO CAPO
IF "%LT1O%"=="4" GOTO TYPO
IF "%LT1O%"=="5" GOTO CAPO
IF "%LT1O%"=="6" GOTO TYPO
IF "%LT1O%"=="7" GOTO CAPO
IF "%LT1O%"=="8" GOTO TYPO
IF "%LT1O%"=="9" GOTO CAPO
:CAPO
:CAPA1O
set CAPA1O=%RANDOM:~0,1%
IF "%CAPA1O%"=="0" set PAS7=A
IF "%CAPA1O%"=="1" GOTO CAPA1O
IF "%CAPA1O%"=="2" set PAS7=B
IF "%CAPA1O%"=="3" GOTO CAPA2O
IF "%CAPA1O%"=="4" set PAS7=C
IF "%CAPA1O%"=="5" GOTO CAPA3O
IF "%CAPA1O%"=="6" set PAS7=D
IF "%CAPA1O%"=="7" GOTO CAPA4O
IF "%CAPA1O%"=="8" set PAS7=E
IF "%CAPA1O%"=="9" GOTO CAPA5O
goto LINE17
:CAPA2O
set CAPA2O=%RANDOM:~0,1%
IF "%CAPA2O%"=="0" set PAS7=F
IF "%CAPA2O%"=="1" GOTO CAPA1O
IF "%CAPA2O%"=="2" set PAS7=G
IF "%CAPA2O%"=="3" GOTO CAPA2O
IF "%CAPA2O%"=="4" set PAS7=H
IF "%CAPA2O%"=="5" GOTO CAPA3O
IF "%CAPA2O%"=="6" set PAS7=I
IF "%CAPA2O%"=="7" GOTO CAPA4O
IF "%CAPA2O%"=="8" set PAS7=J
IF "%CAPA2O%"=="9" GOTO CAPA5O
goto LINE17
:CAPA3O
set CAPA3O=%RANDOM:~0,1%
IF "%CAPA3O%"=="0" set PAS7=K
IF "%CAPA3O%"=="1" GOTO CAPA1O
IF "%CAPA3O%"=="2" set PAS7=L
IF "%CAPA3O%"=="3" GOTO CAPA2O
IF "%CAPA3O%"=="4" set PAS7=M
IF "%CAPA3O%"=="5" GOTO CAPA3O
IF "%CAPA3O%"=="6" set PAS7=N
IF "%CAPA3O%"=="7" GOTO CAPA4O
IF "%CAPA3O%"=="8" set PAS7=O
IF "%CAPA3O%"=="9" GOTO CAPA5O
goto LINE17
:CAPA4O
set CAPA4O=%RANDOM:~0,1%
IF "%CAPA4O%"=="0" set PAS7=P
IF "%CAPA4O%"=="1" GOTO CAPA1O
IF "%CAPA4O%"=="2" set PAS7=Q
IF "%CAPA4O%"=="3" GOTO CAPA2O
IF "%CAPA4O%"=="4" set PAS7=R
IF "%CAPA4O%"=="5" GOTO CAPA3O
IF "%CAPA4O%"=="6" set PAS7=S
IF "%CAPA4O%"=="7" GOTO CAPA4O
IF "%CAPA4O%"=="8" set PAS7=U
IF "%CAPA4O%"=="9" GOTO CAPA5O
goto LINE17
:CAPA5O
set CAPA5O=%RANDOM:~0,1%
IF "%CAPA5O%"=="0" set PAS7=V
IF "%CAPA5O%"=="1" GOTO CAPA1O
IF "%CAPA5O%"=="2" set PAS7=W
IF "%CAPA5O%"=="3" GOTO CAPA2O
IF "%CAPA5O%"=="4" set PAS7=X
IF "%CAPA5O%"=="5" GOTO CAPA3O
IF "%CAPA5O%"=="6" set PAS7=Y
IF "%CAPA5O%"=="7" GOTO CAPA4O
IF "%CAPA5O%"=="8" set PAS7=Z
IF "%CAPA5O%"=="9" GOTO CAPA5O
goto LINE17
:TYPO
:TYPA1O
set TYPA1O=%RANDOM:~0,1%
IF "%TYPA1O%"=="0" set PAS7=a
IF "%TYPA1O%"=="1" GOTO TYPA1O
IF "%TYPA1O%"=="2" set PAS7=b
IF "%TYPA1O%"=="3" GOTO TYPA2O
IF "%TYPA1O%"=="4" set PAS7=c
IF "%TYPA1O%"=="5" GOTO TYPA3O
IF "%TYPA1O%"=="6" set PAS7=d
IF "%TYPA1O%"=="7" GOTO TYPA4O
IF "%TYPA1O%"=="8" set PAS7=e
IF "%TYPA1O%"=="9" GOTO TYPA5O
goto LINE17
:TYPA2O
set TYPA2O=%RANDOM:~0,1%
IF "%TYPA2O%"=="0" set PAS7=f
IF "%TYPA2O%"=="1" GOTO TYPA1O
IF "%TYPA2O%"=="2" set PAS7=g
IF "%TYPA2O%"=="3" GOTO TYPA2O
IF "%TYPA2O%"=="4" set PAS7=h
IF "%TYPA2O%"=="5" GOTO TYPA3O
IF "%TYPA2O%"=="6" set PAS7=i
IF "%TYPA2O%"=="7" GOTO TYPA4O
IF "%TYPA2O%"=="8" set PAS7=j
IF "%TYPA2O%"=="9" GOTO TYPA5O
goto LINE17
:TYPA3O
set TYPA3O=%RANDOM:~0,1%
IF "%TYPA3O%"=="0" set PAS7=k
IF "%TYPA3O%"=="1" GOTO TYPA1O
IF "%TYPA3O%"=="2" set PAS7=l
IF "%TYPA3O%"=="3" GOTO TYPA2O
IF "%TYPA3O%"=="4" set PAS7=m
IF "%TYPA3O%"=="5" GOTO TYPA3O
IF "%TYPA3O%"=="6" set PAS7=n
IF "%TYPA3O%"=="7" GOTO TYPA4O
IF "%TYPA3O%"=="8" set PAS7=o
IF "%TYPA3O%"=="9" GOTO TYPA5O
goto LINE17
:TYPA4O
set TYPA4O=%RANDOM:~0,1%
IF "%TYPA4O%"=="0" set PAS7=p
IF "%TYPA4O%"=="1" GOTO TYPA1O
IF "%TYPA4O%"=="2" set PAS7=q
IF "%TYPA4O%"=="3" GOTO TYPA2O
IF "%TYPA4O%"=="4" set PAS7=r
IF "%TYPA4O%"=="5" GOTO TYPA3O
IF "%TYPA4O%"=="6" set PAS7=s
IF "%TYPA4O%"=="7" GOTO TYPA4O
IF "%TYPA4O%"=="8" set PAS7=u
IF "%TYPA4O%"=="9" GOTO TYPA5O
goto LINE17
:TYPA5O
set TYPA5O=%RANDOM:~0,1%
IF "%TYPA5O%"=="0" set PAS7=v
IF "%TYPA5O%"=="1" GOTO TYPA1O
IF "%TYPA5O%"=="2" set PAS7=w
IF "%TYPA5O%"=="3" GOTO TYPA2O
IF "%TYPA5O%"=="4" set PAS7=x
IF "%TYPA5O%"=="5" GOTO TYPA3O
IF "%TYPA5O%"=="6" set PAS7=y
IF "%TYPA5O%"=="7" GOTO TYPA4O
IF "%TYPA5O%"=="8" set PAS7=z
IF "%TYPA5O%"=="9" GOTO TYPA5O
goto LINE17
:LINE17
set STP1P=%RANDOM:~0,1%
IF "%STP1P%"=="0" GOTO NUBR1P
IF "%STP1P%"=="1" GOTO LTRS1P
IF "%STP1P%"=="2" GOTO NUBR1P
IF "%STP1P%"=="3" GOTO LTRS1P
IF "%STP1P%"=="4" GOTO NUBR1P
IF "%STP1P%"=="5" GOTO LTRS1P
IF "%STP1P%"=="6" GOTO NUBR1P
IF "%STP1P%"=="7" GOTO LTRS1P
IF "%STP1P%"=="8" GOTO NUBR1P
IF "%STP1P%"=="9" GOTO LTRS1P
:NUBR1P
set NUBR1P=%RANDOM:~0,1%
set PAS8=%NUBR1P%
goto LINE18
:LTRS1P
set LT1P=%RANDOM:~0,1%
IF "%LT1P%"=="0" GOTO TYPP
IF "%LT1P%"=="1" GOTO CAPP
IF "%LT1P%"=="2" GOTO TYPP
IF "%LT1P%"=="3" GOTO CAPP
IF "%LT1P%"=="4" GOTO TYPP
IF "%LT1P%"=="5" GOTO CAPP
IF "%LT1P%"=="6" GOTO TYPP
IF "%LT1P%"=="7" GOTO CAPP
IF "%LT1P%"=="8" GOTO TYPP
IF "%LT1P%"=="9" GOTO CAPP
:CAPP
:CAPA1P
set CAPA1P=%RANDOM:~0,1%
IF "%CAPA1P%"=="0" set PAS8=A
IF "%CAPA1P%"=="1" GOTO CAPA1P
IF "%CAPA1P%"=="2" set PAS8=B
IF "%CAPA1P%"=="3" GOTO CAPA2P
IF "%CAPA1P%"=="4" set PAS8=C
IF "%CAPA1P%"=="5" GOTO CAPA3P
IF "%CAPA1P%"=="6" set PAS8=D
IF "%CAPA1P%"=="7" GOTO CAPA4P
IF "%CAPA1P%"=="8" set PAS8=E
IF "%CAPA1P%"=="9" GOTO CAPA5P
goto LINE18
:CAPA2P
set CAPA2P=%RANDOM:~0,1%
IF "%CAPA2P%"=="0" set PAS8=F
IF "%CAPA2P%"=="1" GOTO CAPA1P
IF "%CAPA2P%"=="2" set PAS8=G
IF "%CAPA2P%"=="3" GOTO CAPA2P
IF "%CAPA2P%"=="4" set PAS8=H
IF "%CAPA2P%"=="5" GOTO CAPA3P
IF "%CAPA2P%"=="6" set PAS8=I
IF "%CAPA2P%"=="7" GOTO CAPA4P
IF "%CAPA2P%"=="8" set PAS8=J
IF "%CAPA2P%"=="9" GOTO CAPA5P
goto LINE18
:CAPA3P
set CAPA3P=%RANDOM:~0,1%
IF "%CAPA3P%"=="0" set PAS8=K
IF "%CAPA3P%"=="1" GOTO CAPA1P
IF "%CAPA3P%"=="2" set PAS8=L
IF "%CAPA3P%"=="3" GOTO CAPA2P
IF "%CAPA3P%"=="4" set PAS8=M
IF "%CAPA3P%"=="5" GOTO CAPA3P
IF "%CAPA3P%"=="6" set PAS8=N
IF "%CAPA3P%"=="7" GOTO CAPA4P
IF "%CAPA3P%"=="8" set PAS8=O
IF "%CAPA3P%"=="9" GOTO CAPA5P
goto LINE18
:CAPA4P
set CAPA4P=%RANDOM:~0,1%
IF "%CAPA4P%"=="0" set PAS8=P
IF "%CAPA4P%"=="1" GOTO CAPA1P
IF "%CAPA4P%"=="2" set PAS8=Q
IF "%CAPA4P%"=="3" GOTO CAPA2P
IF "%CAPA4P%"=="4" set PAS8=R
IF "%CAPA4P%"=="5" GOTO CAPA3P
IF "%CAPA4P%"=="6" set PAS8=S
IF "%CAPA4P%"=="7" GOTO CAPA4P
IF "%CAPA4P%"=="8" set PAS8=U
IF "%CAPA4P%"=="9" GOTO CAPA5P
goto LINE18
:CAPA5P
set CAPA5P=%RANDOM:~0,1%
IF "%CAPA5P%"=="0" set PAS8=V
IF "%CAPA5P%"=="1" GOTO CAPA1P
IF "%CAPA5P%"=="2" set PAS8=W
IF "%CAPA5P%"=="3" GOTO CAPA2P
IF "%CAPA5P%"=="4" set PAS8=X
IF "%CAPA5P%"=="5" GOTO CAPA3P
IF "%CAPA5P%"=="6" set PAS8=Y
IF "%CAPA5P%"=="7" GOTO CAPA4P
IF "%CAPA5P%"=="8" set PAS8=Z
IF "%CAPA5P%"=="9" GOTO CAPA5P
goto LINE18
:TYPP
:TYPA1P
set TYPA1P=%RANDOM:~0,1%
IF "%TYPA1P%"=="0" set PAS8=a
IF "%TYPA1P%"=="1" GOTO TYPA1P
IF "%TYPA1P%"=="2" set PAS8=b
IF "%TYPA1P%"=="3" GOTO TYPA2P
IF "%TYPA1P%"=="4" set PAS8=c
IF "%TYPA1P%"=="5" GOTO TYPA3P
IF "%TYPA1P%"=="6" set PAS8=d
IF "%TYPA1P%"=="7" GOTO TYPA4P
IF "%TYPA1P%"=="8" set PAS8=e
IF "%TYPA1P%"=="9" GOTO TYPA5P
goto LINE18
:TYPA2P
set TYPA2P=%RANDOM:~0,1%
IF "%TYPA2P%"=="0" set PAS8=f
IF "%TYPA2P%"=="1" GOTO TYPA1P
IF "%TYPA2P%"=="2" set PAS8=g
IF "%TYPA2P%"=="3" GOTO TYPA2P
IF "%TYPA2P%"=="4" set PAS8=h
IF "%TYPA2P%"=="5" GOTO TYPA3P
IF "%TYPA2P%"=="6" set PAS8=i
IF "%TYPA2P%"=="7" GOTO TYPA4P
IF "%TYPA2P%"=="8" set PAS8=j
IF "%TYPA2P%"=="9" GOTO TYPA5P
goto LINE18
:TYPA3P
set TYPA3P=%RANDOM:~0,1%
IF "%TYPA3P%"=="0" set PAS8=k
IF "%TYPA3P%"=="1" GOTO TYPA1P
IF "%TYPA3P%"=="2" set PAS8=l
IF "%TYPA3P%"=="3" GOTO TYPA2P
IF "%TYPA3P%"=="4" set PAS8=m
IF "%TYPA3P%"=="5" GOTO TYPA3P
IF "%TYPA3P%"=="6" set PAS8=n
IF "%TYPA3P%"=="7" GOTO TYPA4P
IF "%TYPA3P%"=="8" set PAS8=o
IF "%TYPA3P%"=="9" GOTO TYPA5P
goto LINE18
:TYPA4P
set TYPA4P=%RANDOM:~0,1%
IF "%TYPA4P%"=="0" set PAS8=p
IF "%TYPA4P%"=="1" GOTO TYPA1P
IF "%TYPA4P%"=="2" set PAS8=q
IF "%TYPA4P%"=="3" GOTO TYPA2P
IF "%TYPA4P%"=="4" set PAS8=r
IF "%TYPA4P%"=="5" GOTO TYPA3P
IF "%TYPA4P%"=="6" set PAS8=s
IF "%TYPA4P%"=="7" GOTO TYPA4P
IF "%TYPA4P%"=="8" set PAS8=u
IF "%TYPA4P%"=="9" GOTO TYPA5P
goto LINE18
:TYPA5P
set TYPA5P=%RANDOM:~0,1%
IF "%TYPA5P%"=="0" set PAS8=v
IF "%TYPA5P%"=="1" GOTO TYPA1P
IF "%TYPA5P%"=="2" set PAS8=w
IF "%TYPA5P%"=="3" GOTO TYPA2P
IF "%TYPA5P%"=="4" set PAS8=x
IF "%TYPA5P%"=="5" GOTO TYPA3P
IF "%TYPA5P%"=="6" set PAS8=y
IF "%TYPA5P%"=="7" GOTO TYPA4P
IF "%TYPA5P%"=="8" set PAS8=z
IF "%TYPA5P%"=="9" GOTO TYPA5P
goto LINE18
:LINE18
echo %PAS1%%PAS2%%PAS3%%PAS4%%PAS5%%PAS6%%PAS7%%PAS8%

goto LINE10





